### ISSUE TITLE
 'xhj_data.tsv' file is missing

### ISSUE THREAD

**Issue by xianyuxianzi75** [Duguce/ChatBotX#1]
the 'xhj_data.tsv' file is missing in the 'data' dataset, I would appreciate it if you could upload it. thank you.

**Comment by Duguce** [comment]
Hello, the reason for not uploading the dataset `xhj_data.tsv` is because it occupies a large amount of memory, which consequently affects the upload speed. If you require this dataset, perhaps you could leave your email, and I can send it to you later via email.

**Comment by xianyuxianzi75** [comment]
Many thanks for this. xxl959200920257@163.com

**Comment by wuxinkui20-ux** [comment]
你好还有没有xhj_data.tsv，我也想要

**Comment by Duguce** [comment]
> 你好还有没有xhj_data.tsv，我也想要

可以留个邮箱，我找到发给你

**Comment by Ruoke321** [comment]
我去，居然是3年前的项目了吗已经，当时研究大佬的项目研究了好半天

> > 你好还有没有xhj_data.tsv，我也想要
> 
> 可以留个邮箱，我找到发给你

**Comment by Duguce** [comment]
> 我去，居然是3年前的项目了吗已经，当时研究大佬的项目研究了好半天
> 
> > > 你好还有没有xhj_data.tsv，我也想要
> > 
> > 
> > 可以留个邮箱，我找到发给你



哈哈感谢关注，感觉是上个时代的遗物了

**Comment by Ruoke321** [comment]
大佬很强的了，还是ai发展太快了




Sway.
***@***.***

**Comment by wuxinkui20-ux** [comment]
1617941714@qq.com,QQ邮箱

**Comment by wuxinkui20-ux** [comment]
非常想研究一下大佬的东西，15823229721@163.com或者这个邮箱，谢谢

**Comment by wuxinkui20-ux** [comment]
请问找到了吗

**Comment by Duguce** [comment]
@wuxinkui20-ux 发你邮箱了

**Comment by wuxinkui20-ux** [comment]
大佬我用的原始config参数，训练一个epoch就要两天左右吗，需要调什么参数

**Comment by Duguce** [comment]
> 大佬我用的原始config参数，训练一个epoch就要两天左右吗，需要调什么参数

这个感觉你问问AI就好了
